### ISSUE TITLE
Problem z zainstalowaniem VLC

### ISSUE THREAD

**Issue by Memexurer** [vejc1337/vanish#1]

**Comment by Memexurer** [comment]
![yeah](https://cdn.discordapp.com/attachments/1083124495235174500/1100453571352330250/rUFpQMh.gif)
Powyżej znajduje się przedstawienie błędu

**Comment by vejc1337** [comment]
Zostawiam bez komentarza..

**Comment by Memexurer** [comment]
> 

debilu jebany wlasnie zostwailes ten komentarz

**Comment by ekkoree** [comment]
Xdddddddddddddddddddddddddddddd
